name: Playbook pkg Release

on:
  schedule:
     - cron: "30 2 3 * *"
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish-motra-playbook:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    name: Package and Publish Motra Playbook 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

# the licenses are fetched from the local git repository somehow...
# we dont need to setup a license field as part of the labels
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/laboratory-for-safe-and-secure-systems/motra-playbook
          tags: | 
            type=raw,value=latest
          labels: |
            maintainer=Frozenbitz
            org.opencontainers.image.authors=Frozenbitz
            org.opencontainers.image.title=Packaged MOTRA Attack tools for Pentesting and Automation
            org.opencontainers.image.description=A set of tools and scripts, MOTRA uses to create reproducible tests for our dataset generation
            org.opencontainers.image.documentation=https://github.com/Laboratory-for-Safe-and-Secure-Systems/motra-playbook/blob/main/README.md
            org.opencontainers.image.url=https://github.com/Laboratory-for-Safe-and-Secure-Systems/motra-playbook/blob/main
          annotations: |
            maintainer=Frozenbitz
            org.opencontainers.image.authors=Frozenbitz
            org.opencontainers.image.title=Packaged MOTRA Attack tools for Pentesting and Automation
            org.opencontainers.image.description=A set of tools and scripts, MOTRA uses to create reproducible tests for our dataset generation
            org.opencontainers.image.documentation=https://github.com/Laboratory-for-Safe-and-Secure-Systems/motra-playbook/blob/main/README.md
            org.opencontainers.image.url=https://github.com/Laboratory-for-Safe-and-Secure-Systems/motra-playbook/blob/main


      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}